// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listUserOrders = `-- name: ListUserOrders :many
SELECT id, order_number, user_id, status, 
       subtotal_units, subtotal_currency,
       tax_units, tax_currency,
       discount_units, discount_currency,
       total_units, total_currency,
       points_applied, shipping_address, payment_method,
       created_at, updated_at
FROM orders.orders
WHERE user_id = $1
AND ($2::int4 IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListUserOrdersParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Column2 int32       `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListUserOrders(ctx context.Context, arg ListUserOrdersParams) ([]OrdersOrders, error) {
	rows, err := q.db.Query(ctx, listUserOrders,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrdersOrders{}
	for rows.Next() {
		var i OrdersOrders
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.UserID,
			&i.Status,
			&i.SubtotalUnits,
			&i.SubtotalCurrency,
			&i.TaxUnits,
			&i.TaxCurrency,
			&i.DiscountUnits,
			&i.DiscountCurrency,
			&i.TotalUnits,
			&i.TotalCurrency,
			&i.PointsApplied,
			&i.ShippingAddress,
			&i.PaymentMethod,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
