// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Order items/products
type OrdersOrderItems struct {
	// Unique item identifier
	ID pgtype.UUID `json:"id"`
	// Parent order ID
	OrderID pgtype.UUID `json:"order_id"`
	// Product ID
	ProductID pgtype.UUID `json:"product_id"`
	// Product variant ID
	VariantID pgtype.UUID `json:"variant_id"`
	// Product name at time of order
	ProductName string `json:"product_name"`
	// Quantity ordered
	Quantity int32 `json:"quantity"`
	// Unit price in minor units at time of order
	UnitPriceUnits int64 `json:"unit_price_units"`
	// Unit price currency (JPY)
	UnitPriceCurrency string `json:"unit_price_currency"`
	// Total price (unit_price * quantity)
	TotalPriceUnits int64 `json:"total_price_units"`
	// Total price currency (JPY)
	TotalPriceCurrency string `json:"total_price_currency"`
	// Creation timestamp
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Customer orders
type OrdersOrders struct {
	// Unique order identifier
	ID pgtype.UUID `json:"id"`
	// Human-readable order number
	OrderNumber string `json:"order_number"`
	// Customer user ID
	UserID pgtype.UUID `json:"user_id"`
	// Order status: 0=pending, 1=confirmed, 2=shipped, 3=delivered, 4=cancelled
	Status int32 `json:"status"`
	// Subtotal price in minor units (yen has no minor units)
	SubtotalUnits int64 `json:"subtotal_units"`
	// Subtotal currency code (JPY)
	SubtotalCurrency string `json:"subtotal_currency"`
	// Tax amount in minor units
	TaxUnits int64 `json:"tax_units"`
	// Tax currency code (JPY)
	TaxCurrency string `json:"tax_currency"`
	// Discount amount in minor units
	DiscountUnits int64 `json:"discount_units"`
	// Discount currency code (JPY)
	DiscountCurrency string `json:"discount_currency"`
	// Total price in minor units
	TotalUnits int64 `json:"total_units"`
	// Total currency code (JPY)
	TotalCurrency string `json:"total_currency"`
	// Loyalty points applied to order
	PointsApplied int32 `json:"points_applied"`
	// Shipping address as JSONB
	ShippingAddress []byte `json:"shipping_address"`
	// Payment method: 0=credit_card, 1=konbini, 2=points
	PaymentMethod int32 `json:"payment_method"`
	// Creation timestamp
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Last update timestamp
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
