// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders.orders (
    order_number, user_id, status,
    subtotal_units, subtotal_currency,
    tax_units, tax_currency,
    discount_units, discount_currency,
    total_units, total_currency,
    points_applied, shipping_address, payment_method
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id
`

type CreateOrderParams struct {
	OrderNumber      string      `json:"order_number"`
	UserID           pgtype.UUID `json:"user_id"`
	Status           int32       `json:"status"`
	SubtotalUnits    int64       `json:"subtotal_units"`
	SubtotalCurrency string      `json:"subtotal_currency"`
	TaxUnits         int64       `json:"tax_units"`
	TaxCurrency      string      `json:"tax_currency"`
	DiscountUnits    int64       `json:"discount_units"`
	DiscountCurrency string      `json:"discount_currency"`
	TotalUnits       int64       `json:"total_units"`
	TotalCurrency    string      `json:"total_currency"`
	PointsApplied    int32       `json:"points_applied"`
	ShippingAddress  []byte      `json:"shipping_address"`
	PaymentMethod    int32       `json:"payment_method"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.OrderNumber,
		arg.UserID,
		arg.Status,
		arg.SubtotalUnits,
		arg.SubtotalCurrency,
		arg.TaxUnits,
		arg.TaxCurrency,
		arg.DiscountUnits,
		arg.DiscountCurrency,
		arg.TotalUnits,
		arg.TotalCurrency,
		arg.PointsApplied,
		arg.ShippingAddress,
		arg.PaymentMethod,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, order_number, user_id, status,
       subtotal_units, subtotal_currency,
       tax_units, tax_currency,
       discount_units, discount_currency,
       total_units, total_currency,
       points_applied, shipping_address, payment_method,
       created_at, updated_at
FROM orders.orders
WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id pgtype.UUID) (OrdersOrders, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i OrdersOrders
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.SubtotalUnits,
		&i.SubtotalCurrency,
		&i.TaxUnits,
		&i.TaxCurrency,
		&i.DiscountUnits,
		&i.DiscountCurrency,
		&i.TotalUnits,
		&i.TotalCurrency,
		&i.PointsApplied,
		&i.ShippingAddress,
		&i.PaymentMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
