// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOrderItem = `-- name: AddOrderItem :exec
INSERT INTO orders.order_items (
    order_id, product_id, variant_id, product_name, quantity,
    unit_price_units, unit_price_currency, total_price_units, total_price_currency
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (order_id, product_id) DO NOTHING
`

type AddOrderItemParams struct {
	OrderID            pgtype.UUID `json:"order_id"`
	ProductID          pgtype.UUID `json:"product_id"`
	VariantID          pgtype.UUID `json:"variant_id"`
	ProductName        string      `json:"product_name"`
	Quantity           int32       `json:"quantity"`
	UnitPriceUnits     int64       `json:"unit_price_units"`
	UnitPriceCurrency  string      `json:"unit_price_currency"`
	TotalPriceUnits    int64       `json:"total_price_units"`
	TotalPriceCurrency string      `json:"total_price_currency"`
}

func (q *Queries) AddOrderItem(ctx context.Context, arg AddOrderItemParams) error {
	_, err := q.db.Exec(ctx, addOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.VariantID,
		arg.ProductName,
		arg.Quantity,
		arg.UnitPriceUnits,
		arg.UnitPriceCurrency,
		arg.TotalPriceUnits,
		arg.TotalPriceCurrency,
	)
	return err
}

const getOrderItem = `-- name: GetOrderItem :one
SELECT id, order_id, product_id, variant_id, product_name, quantity,
       unit_price_units, unit_price_currency, total_price_units, total_price_currency, created_at
FROM orders.order_items
WHERE id = $1
`

func (q *Queries) GetOrderItem(ctx context.Context, id pgtype.UUID) (OrdersOrderItems, error) {
	row := q.db.QueryRow(ctx, getOrderItem, id)
	var i OrdersOrderItems
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.VariantID,
		&i.ProductName,
		&i.Quantity,
		&i.UnitPriceUnits,
		&i.UnitPriceCurrency,
		&i.TotalPriceUnits,
		&i.TotalPriceCurrency,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT id, order_id, product_id, variant_id, product_name, quantity,
       unit_price_units, unit_price_currency, total_price_units, total_price_currency, created_at
FROM orders.order_items
WHERE order_id = $1
ORDER BY created_at
`

func (q *Queries) GetOrderItems(ctx context.Context, orderID pgtype.UUID) ([]OrdersOrderItems, error) {
	rows, err := q.db.Query(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrdersOrderItems{}
	for rows.Next() {
		var i OrdersOrderItems
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.VariantID,
			&i.ProductName,
			&i.Quantity,
			&i.UnitPriceUnits,
			&i.UnitPriceCurrency,
			&i.TotalPriceUnits,
			&i.TotalPriceCurrency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
