// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddOrderItem(ctx context.Context, arg AddOrderItemParams) error
	CreateOrder(ctx context.Context, arg CreateOrderParams) (pgtype.UUID, error)
	GetOrder(ctx context.Context, id pgtype.UUID) (OrdersOrders, error)
	GetOrderItem(ctx context.Context, id pgtype.UUID) (OrdersOrderItems, error)
	GetOrderItems(ctx context.Context, orderID pgtype.UUID) ([]OrdersOrderItems, error)
	ListUserOrders(ctx context.Context, arg ListUserOrdersParams) ([]OrdersOrders, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdateOrderWithPoints(ctx context.Context, arg UpdateOrderWithPointsParams) error
}

var _ Querier = (*Queries)(nil)
