// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders.orders
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status int32       `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}

const updateOrderWithPoints = `-- name: UpdateOrderWithPoints :exec
UPDATE orders.orders
SET points_applied = $2, discount_units = $3, total_units = total_units - $3, updated_at = NOW()
WHERE id = $1
`

type UpdateOrderWithPointsParams struct {
	ID            pgtype.UUID `json:"id"`
	PointsApplied int32       `json:"points_applied"`
	DiscountUnits int64       `json:"discount_units"`
}

func (q *Queries) UpdateOrderWithPoints(ctx context.Context, arg UpdateOrderWithPointsParams) error {
	_, err := q.db.Exec(ctx, updateOrderWithPoints, arg.ID, arg.PointsApplied, arg.DiscountUnits)
	return err
}
