// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_product.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO catalog.products (name, description, category_id, price_units, price_currency, sku, stock_quantity, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
RETURNING id
`

type CreateProductParams struct {
	Name          *string     `json:"name"`
	Description   *string     `json:"description"`
	CategoryID    pgtype.UUID `json:"category_id"`
	PriceUnits    *int64      `json:"price_units"`
	PriceCurrency *string     `json:"price_currency"`
	Sku           *string     `json:"sku"`
	StockQuantity *int32      `json:"stock_quantity"`
}

// Create a new product in the catalog
// :name, :description, :category_id, :price_units, :price_currency, :sku, :stock_quantity
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.PriceUnits,
		arg.PriceCurrency,
		arg.Sku,
		arg.StockQuantity,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
