// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_product.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE catalog.products
SET deleted_at = NOW(), active = false
WHERE id = $1
`

// Soft delete a product by setting deleted_at timestamp
// :id
func (q *Queries) DeleteProduct(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}
