// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_product_variants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProductVariants = `-- name: GetProductVariants :many
SELECT id, product_id, name, attributes, price_units, price_currency, sku, stock_quantity, created_at, updated_at
FROM catalog.product_variants
WHERE product_id = $1
ORDER BY created_at DESC
`

// Get all variants for a specific product
// :product_id
func (q *Queries) GetProductVariants(ctx context.Context, productID pgtype.UUID) ([]CatalogProductVariants, error) {
	rows, err := q.db.Query(ctx, getProductVariants, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogProductVariants{}
	for rows.Next() {
		var i CatalogProductVariants
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Attributes,
			&i.PriceUnits,
			&i.PriceCurrency,
			&i.Sku,
			&i.StockQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
