// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_top_search_queries.sql

package db

import (
	"context"
)

const getTopSearchQueries = `-- name: GetTopSearchQueries :many
SELECT get_top_search_queries FROM catalog.get_top_search_queries(
    $1
)
`

// Retrieve most popular search queries from the last N days
// Returns top 100 queries with search count and unique user count
// :days_ago
func (q *Queries) GetTopSearchQueries(ctx context.Context, daysAgo *int32) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, getTopSearchQueries, daysAgo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []interface{}{}
	for rows.Next() {
		var get_top_search_queries interface{}
		if err := rows.Scan(&get_top_search_queries); err != nil {
			return nil, err
		}
		items = append(items, get_top_search_queries)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
