// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_product.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProduct = `-- name: GetProduct :one
SELECT id, name, description, category_id, price_units, price_currency, sku, active, stock_quantity, created_at, updated_at
FROM catalog.products
WHERE id = $1
  AND deleted_at IS NULL
`

type GetProductRow struct {
	ID            pgtype.UUID      `json:"id"`
	Name          string           `json:"name"`
	Description   *string          `json:"description"`
	CategoryID    pgtype.UUID      `json:"category_id"`
	PriceUnits    int64            `json:"price_units"`
	PriceCurrency string           `json:"price_currency"`
	Sku           string           `json:"sku"`
	Active        *bool            `json:"active"`
	StockQuantity *int32           `json:"stock_quantity"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

// Get a single product by ID
// :id
func (q *Queries) GetProduct(ctx context.Context, id pgtype.UUID) (GetProductRow, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i GetProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.PriceUnits,
		&i.PriceCurrency,
		&i.Sku,
		&i.Active,
		&i.StockQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
