// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listProducts = `-- name: ListProducts :many
SELECT id, name, description, category_id, price_units, price_currency, sku, active, stock_quantity, created_at, updated_at
FROM catalog.products
WHERE deleted_at IS NULL
  AND ($1::uuid IS NULL OR category_id = $1)
  AND ($2::boolean IS NULL OR active = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListProductsParams struct {
	CategoryID pgtype.UUID `json:"category_id"`
	ActiveOnly *bool       `json:"active_only"`
	Offset     *int32      `json:"offset"`
	Limit      *int32      `json:"limit"`
}

type ListProductsRow struct {
	ID            pgtype.UUID      `json:"id"`
	Name          string           `json:"name"`
	Description   *string          `json:"description"`
	CategoryID    pgtype.UUID      `json:"category_id"`
	PriceUnits    int64            `json:"price_units"`
	PriceCurrency string           `json:"price_currency"`
	Sku           string           `json:"sku"`
	Active        *bool            `json:"active"`
	StockQuantity *int32           `json:"stock_quantity"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

// List products with optional filtering
// :category_id, :active_only, :limit, :offset
func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.CategoryID,
		arg.ActiveOnly,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsRow{}
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CategoryID,
			&i.PriceUnits,
			&i.PriceCurrency,
			&i.Sku,
			&i.Active,
			&i.StockQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
