// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Product categories for hierarchical organization
type CatalogCategories struct {
	// Unique category identifier
	ID pgtype.UUID `json:"id"`
	// Category name
	Name string `json:"name"`
	// Parent category identifier (for hierarchical structure)
	ParentID pgtype.UUID `json:"parent_id"`
	// Category depth level (0 = root, 1 = second level, etc.)
	Level *int32 `json:"level"`
	// Creation timestamp
	CreatedAt pgtype.Timestamp `json:"created_at"`
	// Last update timestamp
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

// Product variants (sizes, colors, etc.)
type CatalogProductVariants struct {
	// Unique variant identifier
	ID pgtype.UUID `json:"id"`
	// Parent product identifier
	ProductID pgtype.UUID `json:"product_id"`
	// Variant name (e.g., "Small", "Blue")
	Name string `json:"name"`
	// Variant attributes as JSON (e.g., {"size": "M", "color": "Blue"})
	Attributes []byte `json:"attributes"`
	// Price in minor units (yen has no minor units)
	PriceUnits int64 `json:"price_units"`
	// Currency code (JPY)
	PriceCurrency string `json:"price_currency"`
	// Stock Keeping Unit for variant
	Sku *string `json:"sku"`
	// Available stock quantity
	StockQuantity *int32 `json:"stock_quantity"`
	// Creation timestamp
	CreatedAt pgtype.Timestamp `json:"created_at"`
	// Last update timestamp
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

// Product catalog items
type CatalogProducts struct {
	// Unique product identifier
	ID pgtype.UUID `json:"id"`
	// Product name
	Name string `json:"name"`
	// Product description (HTML)
	Description *string `json:"description"`
	// Category identifier
	CategoryID pgtype.UUID `json:"category_id"`
	// Stock Keeping Unit
	Sku string `json:"sku"`
	// Price in minor units (yen has no minor units)
	PriceUnits int64 `json:"price_units"`
	// Currency code (JPY)
	PriceCurrency string `json:"price_currency"`
	// Is product active for sale
	Active *bool `json:"active"`
	// Available stock quantity
	StockQuantity *int32 `json:"stock_quantity"`
	// Creation timestamp
	CreatedAt pgtype.Timestamp `json:"created_at"`
	// Last update timestamp
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	// Soft delete timestamp
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}
