// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Product variants (sizes, colors, etc.)
type CatalogProductVariants struct {
	// Unique variant identifier
	ID pgtype.UUID `json:"id"`
	// Parent product identifier
	ProductID pgtype.UUID `json:"product_id"`
	// Variant name (e.g., "Small", "Blue")
	Name string `json:"name"`
	// Variant attributes as JSON (e.g., {"size": "M", "color": "Blue"})
	Attributes []byte `json:"attributes"`
	// Price in minor units (yen has no minor units)
	PriceUnits int64 `json:"price_units"`
	// Currency code (JPY)
	PriceCurrency string `json:"price_currency"`
	// Stock Keeping Unit for variant
	Sku *string `json:"sku"`
	// Available stock quantity
	StockQuantity *int32 `json:"stock_quantity"`
	// Creation timestamp
	CreatedAt pgtype.Timestamp `json:"created_at"`
	// Last update timestamp
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
