// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Create a new product in the catalog
	// :name, :description, :category_id, :price_units, :price_currency, :sku, :stock_quantity
	CreateProduct(ctx context.Context, arg CreateProductParams) (pgtype.UUID, error)
	// Soft delete a product by setting deleted_at timestamp
	// :id
	DeleteProduct(ctx context.Context, id pgtype.UUID) error
	// Get a single product by ID
	// :id
	GetProduct(ctx context.Context, id pgtype.UUID) (GetProductRow, error)
	// Get all variants for a specific product
	// :product_id
	GetProductVariants(ctx context.Context, productID pgtype.UUID) ([]CatalogProductVariants, error)
	// Retrieve most popular search queries from the last N days
	// Returns top 100 queries with search count and unique user count
	// :days_ago
	GetTopSearchQueries(ctx context.Context, daysAgo *int32) ([]interface{}, error)
	// List products with optional filtering
	// :category_id, :active_only, :limit, :offset
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
	// Full-text search for products using PostgreSQL GIN indexes
	// :query, :category_id, :min_price, :max_price, :in_stock_only, :limit, :offset
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error)
	// Fuzzy search for products combining exact full-text match with trigram similarity
	// Supports typo correction and fuzzy matching
	// :search_query, :category_filter, :min_price, :max_price, :stock_only, :fuzzy_threshold
	SearchProductsFuzzy(ctx context.Context, arg SearchProductsFuzzyParams) ([]interface{}, error)
	// Track search query to analytics table for business intelligence
	// Records search query, results count, and optional user_id
	// :search_query, :results_count, :user_id
	TrackSearch(ctx context.Context, arg TrackSearchParams) error
	// Update product fields (only update provided fields)
	// :id, :name, :description, :category_id, :price_units, :active
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error)
}

var _ Querier = (*Queries)(nil)
