// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search_products_fuzzy.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const searchProductsFuzzy = `-- name: SearchProductsFuzzy :many
SELECT search_products_fuzzy FROM catalog.search_products_fuzzy(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type SearchProductsFuzzyParams struct {
	SearchQuery    *string     `json:"search_query"`
	CategoryFilter pgtype.UUID `json:"category_filter"`
	MinPrice       *int64      `json:"min_price"`
	MaxPrice       *int64      `json:"max_price"`
	StockOnly      *bool       `json:"stock_only"`
	FuzzyThreshold *float32    `json:"fuzzy_threshold"`
}

// Fuzzy search for products combining exact full-text match with trigram similarity
// Supports typo correction and fuzzy matching
// :search_query, :category_filter, :min_price, :max_price, :stock_only, :fuzzy_threshold
func (q *Queries) SearchProductsFuzzy(ctx context.Context, arg SearchProductsFuzzyParams) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, searchProductsFuzzy,
		arg.SearchQuery,
		arg.CategoryFilter,
		arg.MinPrice,
		arg.MaxPrice,
		arg.StockOnly,
		arg.FuzzyThreshold,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []interface{}{}
	for rows.Next() {
		var search_products_fuzzy interface{}
		if err := rows.Scan(&search_products_fuzzy); err != nil {
			return nil, err
		}
		items = append(items, search_products_fuzzy)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
