// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: track_search.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const trackSearch = `-- name: TrackSearch :exec
SELECT catalog.track_search(
    $1,
    $2,
    $3
)
`

type TrackSearchParams struct {
	SearchQuery  *string     `json:"search_query"`
	ResultsCount *int32      `json:"results_count"`
	UserID       pgtype.UUID `json:"user_id"`
}

// Track search query to analytics table for business intelligence
// Records search query, results count, and optional user_id
// :search_query, :results_count, :user_id
func (q *Queries) TrackSearch(ctx context.Context, arg TrackSearchParams) error {
	_, err := q.db.Exec(ctx, trackSearch, arg.SearchQuery, arg.ResultsCount, arg.UserID)
	return err
}
