// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_product.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateProduct = `-- name: UpdateProduct :one
UPDATE catalog.products
SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    category_id = COALESCE($3, category_id),
    price_units = COALESCE($4, price_units),
    active = COALESCE($5, active),
    updated_at = NOW()
WHERE id = $6
  AND deleted_at IS NULL
RETURNING id, name, description, category_id, price_units, price_currency, sku, active, stock_quantity, created_at, updated_at
`

type UpdateProductParams struct {
	Name        *string     `json:"name"`
	Description *string     `json:"description"`
	CategoryID  pgtype.UUID `json:"category_id"`
	PriceUnits  *int64      `json:"price_units"`
	Active      *bool       `json:"active"`
	ID          pgtype.UUID `json:"id"`
}

type UpdateProductRow struct {
	ID            pgtype.UUID      `json:"id"`
	Name          string           `json:"name"`
	Description   *string          `json:"description"`
	CategoryID    pgtype.UUID      `json:"category_id"`
	PriceUnits    int64            `json:"price_units"`
	PriceCurrency string           `json:"price_currency"`
	Sku           string           `json:"sku"`
	Active        *bool            `json:"active"`
	StockQuantity *int32           `json:"stock_quantity"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

// Update product fields (only update provided fields)
// :id, :name, :description, :category_id, :price_units, :active
func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.PriceUnits,
		arg.Active,
		arg.ID,
	)
	var i UpdateProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.PriceUnits,
		&i.PriceCurrency,
		&i.Sku,
		&i.Active,
		&i.StockQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
